name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]
on: workflow_dispatch
jobs:
  build:

     RESOURCE-GROUP: rg-eshoponweb-eastus
      location:east-europe
steps:
   995758cb-1f77-4aaf-8774-baea9f949a22 
    - name: devops-webapp-eastus-569532001
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release



